### ISSUE TITLE
Create user endpoint implementation 

### ISSUE THREAD

**Issue by kelumsampath** [INTECS-ITFAC/intecs_webapp_back-end#6]
following attributes need to store :
1. registered date
2. Email
3. Created by (user Id)
4. system generated password (password should store encrypted format) 
For this website, only the existing user can add new user to the system. so, for new user need to store parent user (who created) reference userid [3].

after new user data stored in database, email and password should send to new user's email address (via email) 

every response type should as follow : 
{status:true/false (required) ,massage:"" (required) ,data:{} (optional) }
status true if process successfully done.

**Comment by charindukavishan** [comment]
Can I start this?

**Comment by kelumsampath** [comment]
OK, please proceed.
